### ISSUE TITLE
Edit end dateandtime does not assume that it should be on the same day if date not given

### ISSUE THREAD

**Issue by LuqmanNUS** [cs2103jan2015-t15-1j/main#151]
![screenshot 53](https://cloud.githubusercontent.com/assets/10824198/7038487/2f77899e-dde5-11e4-9fd9-999c52564a14.png)

**Comment by chohanbin** [comment]
If date is supplied in "start" but not in "end," then end date will be the closest date that follows start date. If date is supplied in "end" but not in "start", then start date will be today or tomorrow's date by default.
